# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20171030_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.SubCategory'),
            preserve_default=False,
        ),
    ]
