# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 09:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0012_auto_20171031_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('c_email', models.EmailField(max_length=100)),
                ('c_address', models.CharField(max_length=100)),
                ('c_phone', models.IntegerField(max_length=10)),
                ('c_logo', models.FileField(upload_to=b'')),
                ('c_country', models.CharField(max_length=100)),
                ('c_currency', models.CharField(max_length=1)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
