# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='c_phone',
            field=models.IntegerField(),
        ),
    ]
