# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_pinvoice_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
