# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20171108_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.DecimalField(decimal_places=2, max_digits=8)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=8)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sales', models.IntegerField()),
            ],
        ),
    ]
