# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20171113_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
