# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 09:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20171114_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(default=b'', validators=[django.core.validators.RegexValidator(code=b'invalid_username', message=b"Phone number must be entered in the format: '+91##########'.", regex=b'^[1-9][0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(default=b'', max_length=250),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(default=b'', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_number',
            field=models.IntegerField(default=b'', validators=[django.core.validators.RegexValidator(code=b'invalid_username', message=b"Phone number must be entered in the format: '+91##########'.", regex=b'^[1-9][0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
