# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_product_notify_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='c_country',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='c_currency',
        ),
        migrations.RemoveField(
            model_name='businessprofile',
            name='c_timezone',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default=b'', max_length=100, unique=True),
        ),
    ]
