# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 20:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20171114_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='c_phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(code=b'invalid_username', message=b"Phone number must be entered in the format: '##########'.", regex=b'^[1-9][0-9]{9}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(default=b'', validators=[django.core.validators.RegexValidator(code=b'invalid_username', message=b"Phone number must be entered in the format: '##########'.", regex=b'^[1-9][0-9]{9}$')]),
        ),
    ]
