# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20171114_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='e_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='s_date',
            field=models.DateField(null=True),
        ),
    ]
